### PR TITLE
target FCU/uwp6

### LINKED ISSUE #1: Signal-Windows crashes when the websocket server closes the connection
tldr: nothing we can fix or workaround, we have to wait for a new System.Net.WebSockets.Client release.

https://github.com/dotnet/corefx/issues/17317

Stacktrace:
```
System.Exception: Exception from HRESULT: 0x80072EE2
   at Windows.Networking.Sockets.MessageWebSocketMessageReceivedEventArgs.GetDataReader()
   at System.Net.WebSockets.WinRTWebSocket.OnMessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args)
```

### PR DESCRIPTION
**Pull request by Trolldemorted**
fixes #1 🎉 🎉 🎉

Increases the minimum version to the Fall Creator's Update. Works fine on my desktop at home, and word is on reddit that it has been released to w10m as well.

cc @golf1052

### CODE REVIEW

**Comment by SERVCUBED** [comment]
The Fall Creator's Update currently appears to be in Release Preview on mobile. Could we set the min. target version to the Creator's Update until it has reached production? The libsignal-service-dotnet package would need to be downgraded to 2.5.10.3 for this to work. I can create a PR with these changes if you'd like.

This also seems to have fixed a problem I was having with opening the solution in VS 2017.

**Comment by golf1052** [comment]
I basically agree with @SERVCUBED. We should lower the MinTargetVersion to as low as we can so we have the widest platform support.

Unfortunately #1 would still be a bug on older Win10 versions but since netcore2.0 is out maybe there's a way we can use that to fix it?

**Comment by golf1052** [comment]
Minor update, it looks like a bunch of things got better with the Fall Creators Update. EF Core and SQLite should be much better with UWP in FCU as well.

**Comment by Trolldemorted** [comment]
@SERVCUBED don't worry, we won't merge this without the FCU being available without previews. Unfortunately there might be no easy way to fix #1 without depending on .NETStandard2.0, which requires that we target FCU.

You need Visual Studio 15.4 or higher to use the new uwp sdk, I think. I built and tested this PR using the 15.4 RC, but beware, it is a RC and thus a bit buggy.

Are there devices that support the old CU, but will not support FCU? Are parts of the W10m family already discontinued?

[EF Core and SQLite 2.0 need some tinkering to work with fts5](https://github.com/aspnet/EntityFrameworkCore/issues/10107).

**Comment by SERVCUBED** [comment]
@Trolldemorted Thank you. It appears the problem was that the VS 2017 installer didn't correctly install the SDK for the target version of other branches on both my development machines and just gave a general null reference error when I tried to load the solution. 

As for #1, would it be possible for now to send a keep-alive packet from a background service to prevent the server closing the connection, or is there some other reason for this?

Apparently the Lumia 640(XL) [will not be receiving the FCU](https://www.windowslatest.com/2017/10/18/windows-10-mobile-fall-creators-supported-phones-list/), but may still be able to update through unofficial channels. It's not clear why this is.

**Comment by Trolldemorted** [comment]
Visual Studio 15.4.1 is out, does that one work properly for you?

We are sending keepalives every x seconds, but sometimes the server still closes the network connection, and spurious connection losses always happen (router restart, wifi failure, waking up from standby). Maybe some dirty hacks like depending on a recent version of System.Net.Http and using binding redirects may work?

So targeting FCU instead of CU would exclude Microsoft Lumia 640/640XL and MouseComputer MADOSMA Q501?

Does anyone here have one of these devices, or can we have VS emulate it?

**Comment by SERVCUBED** [comment]
Version 15.4.1 seems to fix almost all my problems 😃 

Does the signal protocol now require websockets? Maybe we could fall back to standard web requests on old devices.

It looks like it's possible to get [emulators](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive) for old SDK versions still so we can see how it would run on those devices.

**Comment by Trolldemorted** [comment]
Great! It is telling me that I have to deploy the project again everytime I restart it.

We could in theory fall back to plain HTTPS, but the performance will degrade, and we would have to do some dirty magic to ensure that the right .NETStandard dlls are linked on the right device - i don't know whether that is possible on UWP.

What is the point of having a progressing standard if you leave devices behind with every iteration? -.-

**Comment by SERVCUBED** [comment]
After some initial thoughts I suggest using compiler flags to switch to HTTPS requests alongside a standalone .patch which can be applied locally to set the dependency references and target versions for both this and libsignal-service-dotnet. This avoids having to detect which framework version is loaded. I believe the Windows store can detect the old target versions in the packages and deploy the most up-to-date one to whichever device supports it.

This is by no means a clean way to do this, but it should work. Hopefully we can find a better way to do this in the future. 

What's your thoughts on this?

**Comment by golf1052** [comment]
Just downloaded the 15254 mobile emulator. UniversalApiContract 5 is not supported. Which also means UWP6 is also not supported. Fall Creators Update on mobile is in name only, not in APIs. That also means we can't bump up the minimum version to FCU unless we want to drop mobile.

**Comment by SERVCUBED** [comment]
@golf1052 My phone has just updated to 15254. This is not exactly the FCU, but seems to contain many changes from it. My guess is the FCU is coming later, but they wanted to get these features to mobile now. There were smaller updates just like this one right before the CU and November update too, so I'm not worrying yet.

**Comment by Trolldemorted** [comment]
superseded by https://github.com/signal-csharp/libsignal-service-dotnet/commit/9e2accd2eb59d02e10ee6f5248150c894145b7b1

**Pull request closed without merging**
