### PR TITLE
Vibrate on message received with app open

### PR DESCRIPTION
**Pull request by SERVCUBED**

### CODE REVIEW

**Comment by golf1052** [comment]
This should probably be configurable per user. Also on startup the device will vibrate a bunch because we process messages one by one at the moment.

**Comment by SERVCUBED** [comment]
Good point! Maybe we could add an option to the conversation settings page for this.

**Comment by golf1052** [comment]
Are there any apps that notify like this while open?

**Comment by SERVCUBED** [comment]
I believe WhatsApp and Messenger vibrate, possibly also showing a banner if the message is not on the currently active thread. I found we needed something when a new message is received as I often set my phone down with the app open while doing something else.

**Pull request merged**
