### PR TITLE
Conversation settings page

### PR DESCRIPTION
**Pull request by golf1052**
Desktop
image

Phone
image

### CODE REVIEW

**Comment by Trolldemorted** [comment]
Looks good!

Minor issues:
- we must stop writing a color to the database when creating a contact, so that we can differ between "default" and "overriden" when the contact name changes
- should we use a 3x5 grid like Signal-Android?

**Comment by golf1052** [comment]
Not sure what you mean by "default" vs "overridden". In Signal-Android the default color is determined by the hashcode of the display name. That is what the reset button will do. When the user changes the contact name we could automatically reset the color again but I think that would be confusing for users, I think it makes more sense to leave it whatever color it is.

Currently using a 4x4 grid because I set it up so you can also set grey.

**Comment by Trolldemorted** [comment]
The reset button is fine, but Signal-Android differs between default (color is null) and overriden (color is xy) colors - we might want to do that too, as it might get important for contact syncs between linked devices. Right now if you change a name, there is no way for Signal-Windows to know whether the old color was explicitly set or if it should use the default derived from a new name.

**Comment by golf1052** [comment]
Ah, I see what you mean. I think it makes more sense to implement the change in another PR though.

**Pull request merged**
