### PR TITLE
receiving and displaying attachments

### PR DESCRIPTION
**Pull request by Trolldemorted**
After reading a bit into git rebase I gave it a shot, and the commit history looks ok!

TODOs:
- [x] ~scroll position is disrupted by lazy-loaded images~
- [ ] attachments are not displayed before the conversation is reloaded
- [ ] it is not possible to restart/abort an attachment download
- [x] ~it is not possible to refuse the automatic download of attachments~
- [x] ~we are abusing the attachment's FileName field to save the GUID (and we don't really need an actual file name (?))~
- [ ] only jpeg, png and gif are displayed

Which of these do we want to tackle before we hit master?

cc @golf1052 @SERVCUBED

### CODE REVIEW

**Comment by golf1052** [comment]
I just fixed 2 in the list. 4 has also been fixed. 5 has been fixed by adding a GUID column to the Attachments table to store the download/upload GUID.

Should rebase this branch off receive-attachments with all the fixes.

**Comment by Trolldemorted** [comment]
Which commit fixes 2?

e852f3fe5a8e2459eecf0bf1f4cfc669aa3e5532 switches to selective downloads, but it stops automatic downloads which users might want if they have wifi/unmetered connections. We could postpone automatic downloads, though.

With e852f3fe5a8e2459eecf0bf1f4cfc669aa3e5532's guid field, can we remove FileName altogether?

**Comment by golf1052** [comment]
Which commit fixes 2?
- If you mean attachment images aren't displayed before the conversation is reloaded than that is not fixed. If you mean just displaying sent attachments correctly that is here 0c365e13ed7381a48a6a8364b6fef64689c4597e

e852f3f switches to selective downloads, but it stops automatic downloads which users might want if they have wifi/unmetered connections. We could postpone automatic downloads, though.
- Yes it should be pretty easy to put automatic downloads behind a settings flag. Good candidate for a intro task.

With e852f3f's guid field, can we remove FileName altogether?
- Yes

**Comment by Trolldemorted** [comment]
cherry-picked e852f3fe5a8e2459eecf0bf1f4cfc669aa3e5532!

Now we use the Guid field, have a fixed height, and Signal-Android like download buttons.

**Comment by golf1052** [comment]
I assume we'll handle uploading in a separate PR?

**Comment by Trolldemorted** [comment]
I suppose so, as this diff is already huge and we have still a lot to do.

Can we somehow easily cancel our downloading tasks (only the tasks managing the download, not the download itself) when we go into suspend?

**Comment by Trolldemorted** [comment]
Unfortunately a420a104f5bb15d147fac563ee38b7ed1c02107c broke our scrolling behaviour: The images are lazy-loaded, and if the last few messages before the last seen message contain attachments the height above the last seen message changes and it is scrolled out of view.

I assume Signal-Android has the same problem, since their attachments have a fixed width and height.

What is the advantage of using `GetImagePropertiesAsync`?

**Pull request closed without merging**
