### PR TITLE
fixed Add-Migration command

### PR DESCRIPTION
**Pull request by ShelbyBoss**
For me the Add-Migration command only works when I have the project `Signal-Windows` selected and add `-Project Signal-Windows.Lib` the command.

### CODE REVIEW

**Comment by golf1052** [comment]
This is what works for me 
image

Are you setting the startup project as Signal-Windows.Lib?

**Comment by ShelbyBoss** [comment]
I have set Signal-Windows.Lib as startup project
image

**Comment by golf1052** [comment]
Ah that might be the problem. The startup project should be set to Signal-Windows.

**Comment by ShelbyBoss** [comment]
But then I need specify the project:
image

**Comment by golf1052** [comment]
Here's my configuration

image

**Comment by ShelbyBoss** [comment]
Ah, now I get it. I didn't notice that there is difference between "Default project" and "Startup Project". My bad.

I updated the readme to clarify that.

**Pull request merged**
